### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by miguelmich** [cakebake/jquery-breakpoint-check#1]
Hello @cakebake ,

Just wanted to let you know that I just registered the bower package of your repository in order to make releases available from bower.

To install this repo with bower use `bower install jquery-breakpoint-check` If you want to update your documentation :)

PD: Thanks for this awesome and clean work!

**Comment by cakebake** [comment]
I am happy that you can use the small script :) I have not yet worked with bower, does that require a file `bower.json` in the root of the repository?

**Comment by miguelmich** [comment]
It is not necessary to register a package, but it would be great to have it, if you want  I can make a pull request with the bower.json file

**Comment by cakebake** [comment]
The pull request would be very nice. thx
